baseurl = "/"
languageCode = "en-us"
title = "pistalix"
[[menu.main]]
name = "Pistalix TV"
parent = "products"
url = "/TV"
weight = 8
[[menu.main]]
name = "New"
url = "/new"
weight = 2
[[menu.main]]
name = "Contact us"
url = "/contact/"
weight = 9
[[menu.main]]
name = "Table"
url = "/table"
weight = 7
[[menu.main]]
name = "Services"
url = "/services/"
weight = 6
[[menu.main]]
name = "Careers"
url = "/Careers/"
weight = 4
[[menu.main]]
name = "About Us"
url = "/aboutus/"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
